# Generated by Django 3.2.9 on 2021-11-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_site', '0002_marks_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks_data',
            name='Grade',
            field=models.CharField(default='', max_length=5),
        ),
    ]
